spring:
  application:
    name: fakebank
  datasource:
    url: jdbc:mysql://localhost:3306/fakebank?serverTimezone=GMT-3
    hikari:
      connection-test-query: select 1
      idle-timeout: 5000
      max-lifetime: 120000
      maximum-pool-size: 5
      minimum-idle: 5
  cloud:
    vault:
      uri: ${VAULT_ADDR}
      token: ${VAULT_TOKEN}
      connection-timeout: 5000
      read-timeout: 15000
      database:
        enabled: true
        role: mysql-demo-role
        #role: oracle-demo-role
        backend: database
        username-property: spring.datasource.username
        password-property: spring.datasource.password
  config:
    import: vault://
spring.cloud.compatibility-verifier.enabled: false